import '../styles/index.scss';

const metadata = {
    title: '3D Demo | Schulze Baek', description: 'Generated by create next app',
};

function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>{children}</body>
        </html>
    );
}

export {
    metadata,
    RootLayout as default,
}