import '../styles/index.scss';
import PageMenu from '@/components/PageMenu';

const metadata = {
    title: '3D Demo | Schulze Baek', description: 'Generated by create next app',
};

function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
            <PageMenu />
            {children}
        </body>
        </html>
    );
}

export {
    metadata,
    RootLayout as default,
}